### ISSUE TITLE
Adding medium and hard levels in levels.cpp

### ISSUE THREAD

**Issue by XDRAGON2002** [pratul20/Typing-Master#1]
Currently only easy level has been implemented and the medium and hard levels need to be implemented as well.

**Comment by pratul20** [comment]
In Classic mode, easy, medium and hard depends only on the type of text.
For eg: In easy, there will be simple sentences
In medium, there will be some stanzas of poem, in which difficult words along with punctuation marks is there.

All we need is just a database from some typing site.. so instead of implementing medium and hard, you can implement the file system for now

**Comment by XDRAGON2002** [comment]
Okay got it

**Comment by XDRAGON2002** [comment]
Opened PR #3 that fixes this issue.
